changed os.removedirs -> shutil.rmtree
This patch changes os.removedirs to shutil.rmtree, because
os.removedirs cannot remove directories recursivly.

Without this patch you get an error message like:

OSError: [Errno 39] Directory not empty:

when a cleanup of a corrupt cache dir should be done